baseUrl: "https://lqhl.me/"
theme: hugo-bearblog

publishDir: docs

title: "巴别之塔 - Tower of Babel"
author:
  name: "Qin Liu"
  email: lqgy2001@gmail.com
copyright: "Copyright © 2023, Qin Liu."
languageCode: zh

menu:
  main:
  - name: Research
    url: /research/
  - name: Notion
    url: https://lqhl.notion.site/Qin-s-Digital-Garden-8032c0f3ab344dc3b493800a57209059
  - name: Github
    url: https://github.com/lqhl

# Generate a nice robots.txt for SEO
enableRobotsTXT: true

taxonomies:
  tag: tags

permalinks:
  blog: "/blog/:filename"
  tags: "/tags/:slug"

params:
  title: "巴别之塔"
  description: "lqhl's blog"
  favicon: "images/logo.png"
  utterances:
    repo: "lqhl/lqhl.me"
    issue_term: "pathname"
    label: "comment"
    theme: "github-light"

markup:
  highlight:
    style: github
  goldmark.renderer.unsafe: true
